### ISSUE TITLE
Getting a call while typing out a contact soft locks the game

### ISSUE THREAD

**Issue by moyogii** [Monolith-RP/issues#105]
### Describe The Bug

Found a bug with the monophone if you get a call while typing out a contact it soft locks the game and your mouse stays stuck as the text tool you use to copy paste the little I, slaying opening chat holding C pressing ESC nothing fixes it other than rejoining.

### To Reproduce

Type out a contact and have someone call you.

### Expected Behavior

It should not do this.

**Comment by DevulTj** [comment]
Should be fixed with the call system redo. Reopen if this is not true
