### ISSUE TITLE
Some properties are not rentable through the MonoPhone

### ISSUE THREAD

**Issue by moyogii** [Monolith-RP/issues#110]
### Describe The Bug

Some properties fail to rent and then refund you your money back and give no reason why it failed.

### To Reproduce

Open the MonoPhone and attempt to rent the Steakhouse on Monoford v1k

### Expected Behavior

It should let you rent the property.

**Comment by DevulTj** [comment]
So we have this fixed now, right? @m4rkey

**Comment by moyogii** [comment]
Yes.
