### ISSUE TITLE
Apparently you cannot call anybody who is not a contact (MonoPhone)

### ISSUE THREAD

**Issue by moyogii** [Monolith-RP/issues#111]
### Describe The Bug

Apparently, according to players, you cannot call others via Phone number # unless they are a contact in your phone.

### To Reproduce

Go to the dial pad, call somebody, and it does not call them, it just endlessly rings.

### Expected Behavior

It should function as a normal phone call.

**Comment by DevulTj** [comment]
I haven't been able to replicate this

**Comment by moyogii** [comment]
This seems to be fixed.
