### ISSUE TITLE
When texting somebody else, if you get texted the new text message will mesh with the current conversation (MonoPhone)

### ISSUE THREAD

**Issue by moyogii** [Monolith-RP/issues#112]
### Describe The Bug

Basically, when you are texting another individual and you receive a text message that text message will merge into the current conversation that you have open if it is not that person.

### To Reproduce

Go to MonoMessage start a conversation, text someone and then have someone text you while you are texting them.

### Expected Behavior

You should only see text messages from the conversation you have open and other text messages should be notifications

**Comment by DevulTj** [comment]
Should be fixed. Please test
