### ISSUE TITLE
Services & 911 App call 911 caller button doesn't work 

### ISSUE THREAD

**Issue by DevoTan** [Monolith-RP/issues#155]
### Describe The Bug

The blue phone button that appears when you double click a 911 call on the call map does not call the phone number displayed

### To Reproduce

Have someone make a 911 call
Government employee opens Services & 911 app
Government employee clicks on the call
Government employee attempts to click the blue phone icon

### Expected Behavior

The 911 caller will not receive the call.

### Additional Context

If I am mistaken as to what the button's actual purpose is I would love to know what it really does.

Video showing bug steps and result show above:
https://www.youtube.com/watch?v=qU-R0n66qv4

**Comment by RedSpeeds** [comment]
In addition please allow us to set a GPS compass to the 911 call its simply stupid this is not a possibility

**Comment by R4K0** [comment]
Call button was a placeholder, there was no convenient way to initiate a call from an another app. @DevulTj is this now possible?


> In addition please allow us to set a GPS compass to the 911 call its simply stupid this is not a possibility

Could you please create a new feature suggestion in this repository, so I can track it?

**Comment by DevulTj** [comment]
I don't think we have a nice helper for it, but calling doesn't open a specific app anymore - so it should be easier than before.

**Comment by R4K0** [comment]
Done.
