### ISSUE TITLE
Make cops take a quick ingame test in the police npc before joining

### ISSUE THREAD

**Issue by Javichu59** [Monolith-RP/issues#156]
### Describe The Feature

You go into the police NPC and you make a test to access the police roles, like the driving license but with the pd jobs, maybe this will make people be better cops and remind them of the rules + teach them stuff before actually playing as a cop.

### Why Would You Like This Feature?

Improves rp, reminds people of the PD rules.

**Comment by moyogii** [comment]
@DevulTj This is similar to what I said in our DMs.

**Comment by DevoTan** [comment]
This probably should only either popup once in a while or on your first join because I can already imagine the races to do the test to get the LT slot from the guy that just logged off.

**Comment by Javichu59** [comment]
> This probably should only either popup once in a while or on your first join because I can already imagine the races to do the test to get the LT slot from the guy that just logged off.

You dont need to have a free slot to make the test

**Comment by DKDiamond04** [comment]
I feel like this would be quite monotonous after awhile, I think the PD Handbook should just be enforced as rules. Cops get away with what I like to call “RDM within the rules”.
