### ISSUE TITLE
Cooking with spookfest potions

### ISSUE THREAD

**Issue by BarryGunderson** [Monolith-RP/issues#160]
### Describe The Feature

I think it would be fun if you could use the new spook fest potions in a meal that you cant make. I know about half of the potions have negative effects and that makes them pretty much useless besides tricking people once. I think it would be fun and cause some good RP if you could put these into the player cooked meals. For example you could assassinate the mayor by putting a death cap potion in his food. 

![645345354](https://user-images.githubusercontent.com/93226738/138962541-3c3e1076-f7dc-452c-b4fb-9e415ad5ce2d.PNG)

As of right now I dont know if you can use the spices slot, I have tried a few things I think would work but no luck so far.

### Why Would You Like This Feature?

I think it would be fun and make good RP as well as give more use for the spook fest potions

### Suggested Solution

Allow players to use spookfest potions under the spice tab when making meals.

### Considered Alternatives

n/a

**Comment by moyogii** [comment]
This should already be the case. I will look into this and see what happened.

**Comment by moyogii** [comment]
Hi there, I verified that this is already possible. However they were using the incorrect slot and now will operate as a drink. You should see this change take effect in Patch 2.0.6.
