### ISSUE TITLE
Add a remington or a wooden pump shotgun

### ISSUE THREAD

**Issue by Javichu59** [Monolith-RP/issues#161]
### Describe The Feature

Good for the pine county deputies also a pretty good change since cops only get a m3...doesn't really makes any sense would be cool if cops got a different shotgun ngl

### Why Would You Like This Feature?

Gun variety, adds more aesthetic to the pine deputies.

**Comment by moyogii** [comment]
This is not something we are looking to do currently as certain things will be changing in the future.
