### ISSUE TITLE
MP5 PD 30 rnd mag issue

### ISSUE THREAD

**Issue by Javichu59** [Monolith-RP/issues#163]
### Describe The Bug

If you choose to get the 30rnd mag on an MP5 as a cop and get in a car your gun will unload itself everytime and its really annoying for shootings, this has been a thing since rockford (4 years ago)

### Expected Behavior

The gun shouldnt unload itself

### Additional Context

Mp5 is bae

**Comment by RedSpeeds** [comment]
Same with AR15

**Comment by DevulTj** [comment]
Fixed with MP5
