### ISSUE TITLE
Chunks still go to 107%

### ISSUE THREAD

**Issue by Bahalu** [Monolith-RP/issues#172]
### Describe The Bug

I thought this issue was fixed, because I saw it in the discord & they said it was fixed but this is clearly not the case. I've seen it more than four times since the message saying it was fixed was sent & I've got proof of it that I'll attach to this message
![image_2021-10-30_145542](https://user-images.githubusercontent.com/93448637/139555355-f2105968-00fd-4d83-8934-835bd8182389.png)

### To Reproduce

1. Mine the chunk
2. Wait for it to refresh
3. It'll show 107% sometimes

### Expected Behavior

1. Mine the chunk
2. Wait for it to refresh
3. It'll show 100%

**Comment by DevulTj** [comment]
Thank you, it'll be looked into

**Comment by DevulTj** [comment]
Should be fixed.
