### ISSUE TITLE
Add more raidable locations on southside

### ISSUE THREAD

**Issue by RedSpeeds** [Monolith-RP/issues#181]
### Describe The Feature

Add more lockers/vaults in places like gas stations.

### Why Would You Like This Feature?

Since we will be staying on southside for a little while longer having only 1 raidable location seems silly with the hour long cooldown therefor id like if there would be more raidable locations added.

### Suggested Solution

Adding more raid zones thru D-Heist

### Considered Alternatives

Cutting the cooldown for jewlery heist in half

**Comment by DevulTj** [comment]
We're not staying long enough for this
