### ISSUE TITLE
Allow Jobs to wear their bought hats

### ISSUE THREAD

**Issue by RedSpeeds** [Monolith-RP/issues#184]
### Describe The Feature

Allow Jobs to wear hats from the inventory

### Why Would You Like This Feature?

You spend so much time to grind the items needed to buy the hats and if your a government player your not even able to wear them i find this unfair considering the amount of effort/money you spent on these hats

**Comment by moyogii** [comment]
I think jobs need to keep that sense of realism that they have in addition to the fact that jobs already have cosmetics and some will get changed in the future by allowing you to wear other cosmetics it will just look a bit funky.
