### ISSUE TITLE
Ambulance spawn point is not correct

### ISSUE THREAD

**Issue by xWaller0119** [Monolith-RP/issues#188]
### Describe The Bug

On the right side of the double parking lane, in the emergency lane, the rear end of the regular ambulance clips into the wall and gets stuck and I am unable to spawn a new one in the other lane because it says "Move vehicle closer."

https://i.imgur.com/kn1vccK.jpeg

### To Reproduce

Spawn a regular ambulance via NPC (obviously) and check the rear end of it, as it clips into the wall.

### Expected Behavior

Not clip into the wall..?

**Comment by moyogii** [comment]
Fixed in next patch.
