### ISSUE TITLE
PD drone

### ISSUE THREAD

**Issue by Javichu59** [Monolith-RP/issues#192]
### Describe The Feature

A deployable drone for SWAT officers able to be shot down by criminals

### Why Would You Like This Feature?

Adds in teamwork, realism, used for seeing if there are more enemies inside the building you are raiding or the enemy positions, can be also shot down by criminals and its noisy so it would be easy to spot.

**Comment by aaddaammgg** [comment]
I believe this has been discussed before in discord, but I think it is cool to have drones. However, it would take a lot of time/resources to create a fully functioning drone.

**Comment by Javichu59** [comment]
Just take a drone addon from the workshop + i was the one discussing it.

**Comment by DevulTj** [comment]
I don't think we'll do this
