### ISSUE TITLE
2 life rule for PD

### ISSUE THREAD

**Issue by DKDiamond04** [Monolith-RP/issues#193]
### Describe The Feature

Only allow one life for Police, every single time I am on Chief and their is a raid. They all say "we have 2 lifes, just rush in". This is basic FTVL. At the end of the day cops should be trying to live not frag out.

### Why Would You Like This Feature?

Stop FTVL which cops do not get punished for either way

### Suggested Solution

remove 2 life rule and have just like any other player

### Considered Alternatives

Inform PD and enforce FTVL on cops, its not their duty to take down criminals within the first 30 seconds of arriving on scene.

**Comment by DevulTj** [comment]
This is for development, not rules.
