### ISSUE TITLE
better fishing

### ISSUE THREAD

**Issue by Its-Valentino** [Monolith-RP/issues#199]
### Describe The Feature

Better fishing and make boats not shit

### Why Would You Like This Feature?

the small, medium and large bait are a great improvement but boats remain useless, especially now we're on southside and the new bait only leaves a couple of fish able to get caught, a bit boring if you ask me. 

### Suggested Solution

First of all more fish for every level of bait, Salmon, Cod, Herring etc. And for a while we had a pretty cool new fishing system where there were specific areas to fish for specific fish (these removed fish are still listen in the skill menu under cooking btw) but unfortunately it was pretty bugged. I suggest adding this back but with the style in how fishing currently works in just adding specific areas for specific fish to make boats useful again but leaving the actual fishing and catching mechanics the same. 

Also a small but pretty nice change would be to not lock the screen (and possibly movement) while fishing anymore. It was a bit of a useless and simply annoying change, for some reason the thrown bait uses some weird rendering method so if you throw bait and it leaves your screen it doesn't move and you wont be able to catch fish. I assume this is done for optimization and it isn't horrible but with the camera lock, there are occasions where the bait going too high and because the camera lock you can't render the bait and as such can't catch any fish. When staff members fish and quickly go in and back out of noclip it unfreezes their screen and movement so it should be possible to change back I'd imagine. 

### Considered Alternatives

At least unfreezing the camera and movement would be a welcomed change, ideally though more fish and specific fish areas as well.

**Comment by moyogii** [comment]
The old system was removed as it broke the physics in the game causing things to fall through the map it wont be seeing a return. I think the fishing system is fine as is and any other changes will be added in the form of new fish, new bait and maybe other forms of obtaining fish.
