### ISSUE TITLE
Southside PD Garage Vent, Car Damage

### ISSUE THREAD

**Issue by JacubRSTNC** [Monolith-RP/issues#201]
### Describe The Bug

Driving a vehicle near the vent inside of the Southside PD heavily increases the damage the vehicle takes. So if u hit a wall at like 10 mph it goes from 100% to 25% health. Instead of 100% to 98%

### To Reproduce

1. Spawn a vehicle
2. Drive into the Southside PD Garage
3. Be close to the vent in the garage (whilst it is active)
4. And hit a wall at a slow speed (see the amount of damage)

### Expected Behavior

Vehicle damage shouldn't be affected

**Comment by RedSpeeds** [comment]
Gonna say this is a map issue and could possibly not be fixed

**Comment by DevulTj** [comment]
Southside related, can't fix
