### ISSUE TITLE
Limo Driver

### ISSUE THREAD

**Issue by DKDiamond04** [Monolith-RP/issues#204]
### Describe The Feature

The mayors limo has an option to removed all the presidential decor on it. I thought making a job after bus driver would be a cool idea.

### Why Would You Like This Feature?

I think orgs would use this a lot to show off around town. 
Gives another reason for people to level up the transportation skill.

### Suggested Solution

Add mayors limo without presidential decor as a higher job transportation skill

### Considered Alternatives

find a new limo since the mayors limo does have spike proof tires.

**Comment by moyogii** [comment]
No. I think bus driver will suffice.
