### ISSUE TITLE
Show your I.D. and vehicle papers is showing to the wrong person if someone is in your vehicle

### ISSUE THREAD

**Issue by aaddaammgg** [Monolith-RP/issues#209]
### Describe The Bug

If you are in a vehicle and someone else is in your vehicle and you attempt to show your I.D. or vehicle papers it will show the passenger in your vehicle instead of the person(Officer) outside of your vehicle

### To Reproduce

1. Get in a car.
2. Have someone else get in your car.
3. Hold 'E' and click "Show your I.D." or "Show Vehicle Papers".

### Expected Behavior

It should show the I.D. and/or vehicle papers to the people outside of your vehicle instead of the people inside of your vehicle.

**Comment by moyogii** [comment]
This should be resolved in Update 2.1
