### ISSUE TITLE
Phonetic Alphabet training for police

### ISSUE THREAD

**Issue by lZoZol** [Monolith-RP/issues#210]
### Describe The Feature

In Real life cops uses phonetic alphabet to prevent miscommunication

Just like in real life I think it is definitely usefull in this game
As chief of the pd it's mandatory to know the phonetic alphabet inside out

### Why Would You Like This Feature?

Because sometimes if someone speak a license plate and there is miscommunication or just to much noice on the radio, it is still possible to know the license plate because of the word they use

### Suggested Solution

It's a training you can follow to learn them, study them and the doing a test, if you get 22/26 you Passed the training and then it Count as training for chief
If you failed it's an "invalid" training and you need to redo it

### Considered Alternatives

N/A

**Comment by DKDiamond04** [comment]
Don’t think it’s needed, you can just use /rc “license plate” 

If someone asks we to run a plate, I ask them to do that then.

**Comment by DevulTj** [comment]
This is for development, not police training
