### ISSUE TITLE
Hunger/Thirst sounds 

### ISSUE THREAD

**Issue by DKDiamond04** [Monolith-RP/issues#211]
### Describe The Bug

Hunger/Thirst sounds when disabled can still be heard

### To Reproduce

1. Go to 'inventory'
2. Click on 'settings (double cog icon)'
3. Scroll down to 'enable hunger/thirst sounds'
4. click to disable (red zone)
5. still able to hear noises

### Expected Behavior

unable to hear noises

### Additional Context

This has only happened to me today (11/12/2021)

### Log Output

```shell
N/A
```

**Comment by DevulTj** [comment]
Fixed for update 2.1
