### ISSUE TITLE
Combat Heal

### ISSUE THREAD

**Issue by DKDiamond04** [Monolith-RP/issues#215]
### Describe The Feature

Block healing from others when in combat.

### Why Would You Like This Feature?

Combat healing is annoying and unless a staff is their or watching, its annoying when you are on cop and situations are voided.

### Suggested Solution

If possible, block medics from being able to heal others if they have the combat status.

### Considered Alternatives

N/A

**Comment by moyogii** [comment]
I am going to say this is more of a rule issue than a gamemode issue currently. If you suspect someone of combat healing then please make a report and have it dealt with.
