### ISSUE TITLE
Calling not working

### ISSUE THREAD

**Issue by DevoTan** [Monolith-RP/issues#222]
### Describe The Bug

When you attempt to call someone they will not receive the call and it will display, "Unknown" even if you have them as a contact.

### To Reproduce

1. Call a Contact (or from keypad)
2. See "Calling Unknown"

### Expected Behavior

The Caller will not receive the call.

### Additional Context

It's been broken for a while. Just an assumption but I believe the 911 Blue Call button could have something to do with it not working.

**Comment by DevulTj** [comment]
I'm relatively certain this is fixed but please let me know if it isn't. I can't test this easily

**Comment by DevoTan** [comment]
I'll check the first chance I get.
