### ISSUE TITLE
Deployable(s) broke for owned properties

### ISSUE THREAD

**Issue by xWaller0119** [Monolith-RP/issues#223]
### Describe The Bug

I have tried and tried, multiple properties, multiple friends (with keys and without to test) and myself, and I can not seem to get a Repair Bench deployed. Yes I am on my property. Been an issue ever since the deployment on property only thing was implemented for whatever reason. There might be other deployables with the same issue but this is the only one i've tried so far.

### To Reproduce

Try to deploy a repair bench on property and/or have a friend with keys try and deploy it aswell. Doesn't work.

### Expected Behavior

Let me deploy my repair bench and other friends that have my keys to house/door or whatever, deploy them aswell.

**Comment by DevulTj** [comment]
Fixed in 2.1
