### ISSUE TITLE
uno

### ISSUE THREAD

**Issue by Its-Valentino** [Monolith-RP/issues#226]
### Describe The Feature

uno card game in casino

### Why Would You Like This Feature?

uno is the best game ever and I want to rdm people when they +4 me

### Suggested Solution

uno. in. casino. 

### Considered Alternatives

there is no alternative to uno

**Comment by RedSpeeds** [comment]
😕

**Comment by moyogii** [comment]
While this is something that would be cool to add it's a bit out of scope currently. I think if we were to do this it would be a spur of the moment thing.
