### ISSUE TITLE
paper rolls being traded and not being able to work (LSD)

### ISSUE THREAD

**Issue by DIREDURATION** [Monolith-RP/issues#228]
### Describe The Bug

When you are doing LSD and u get the flask out of the mini fridge u are supposed to put a paper roll on top of it to turn it into LSD 
However when u trade someone the paper roll and they deploy it it doesnt combine with the flask to make  LSD here is the video of me proving this bug 

                                                         got to my YT channel https://www.youtube.com/channel/UCpNHHsFE0Fa2w2KmJAuOjHQ/ and watch the only video there

### Expected Behavior

for the things to turn into LSD

**Comment by moyogii** [comment]
I believe this to be a ownership issue. I think the owner of the LSD was not the one trying to combine the paper towel.

**Comment by DevulTj** [comment]
Intended behavior
