### ISSUE TITLE
Bug in scrapyard

### ISSUE THREAD

**Issue by Parker111333** [Monolith-RP/issues#229]
### Describe The Bug

If you go into scrapyard use the ladder using e go to the top, then press e on the ladder 2 times it phases you through the window 

### To Reproduce

1. Go to scrapyard
2. Click on the ladder the one inside any of the 2 
3. Press e 2 times on ladder once at the top
4. Boom your phased through the glass 

### Expected Behavior

Phase through window making you not use a lock pick 

### Additional Context

Nothing 

### Log Output

```shell
Nothing
```

**Comment by Parker111333** [comment]
I was trying to open it with keys but I had none because my friend went off and that’s how I figured this out

**Comment by DevulTj** [comment]
It's ok we're not staying on this map long
