### ISSUE TITLE
Machette seems to ignore armor

### ISSUE THREAD

**Issue by RedSpeeds** [Monolith-RP/issues#236]
### Describe The Bug

While playing as police i sometimes get 1 shotted by a machette even if im full health and full armor im not sure why this is the case but this it extremely difficult to protect yourself if the person is already standing close by

### To Reproduce

1. Get a machette
2. Get a cop (Full health, armor)
3. Stab cop from behind
4. Watch him die instantly

### Expected Behavior

The machette should not be a one hit kill it should require more to kill a person with full armor and health than 1 stab in the back

**Comment by DevulTj** [comment]
Fixed since HL2 RP
