### ISSUE TITLE
Police armor not detected

### ISSUE THREAD

**Issue by RedSpeeds** [Monolith-RP/issues#237]
### Describe The Bug

During shootouts we felt as if police died faster than criminals so we decided to test to see if this is the case and during testing we discovered police armor is not calculated during damage calculations we also found out why due to the fact police armor is equipped directly into the armor slot for some reason the server's combat system is unable to detect it and will ignore it. The current fix for it is unequiping the armor and reequiping it.

### To Reproduce

1. Buy police armor
2. Do a damage test
3. Repeat 1 put take it off and put it back on again
4. See the difference between damage

### Expected Behavior

Police armor should be detected by the combat system and negate the damage as intended

**Comment by Gamer3232** [comment]
Confirmed by multiple ex devs and current ones. Police armor does nothing. Never bought it found out I was doing just as bad in police fights.

**Comment by RedSpeeds** [comment]
Alright so me and boris did some extensive testing and concluded the following civilian armor protects better against headshots than police armor does see https://medal.tv/games/garrys-mod/clips/6YiFjpe9rmBSZ/d1337lO44Qjf?invite=cr-MSxhVTYsMjE1NjEwMTUs

**Comment by DevulTj** [comment]
Fixed
