### ISSUE TITLE
Detective Bugs

### ISSUE THREAD

**Issue by JacubRSTNC** [Monolith-RP/issues#238]
### Describe The Bug

- [x] Detectives are unable to rent properties
- [x] Body bags don't spawn for detectives upon respawn
- [x] Detectives are unable to pickup confiscatable items.

### To Reproduce

Bug 1:
Attempt to rent a property whilst on duty as a Detective.

Bug 2:
Have a drop on death item on you and slay yourself. Watch no body bag appear on respawn.

Bug 3:
Attempt to pick up an automatic rifle, lockpick or some other confiscatable item.

### Expected Behavior

Bug 1:
The detective should be able to rent a property without issues.

Bug 2:
A body bag should spawn with all drop on death items upon the death of the detective.

Bug 3:
The items should appear in the detectives inventory, and instead of it instantly being confiscated. Have an option to confiscate.

**Comment by RedSpeeds** [comment]
I wouldn't call bug 3 a bug more a feature otherwise detectives would bank class 3's

**Comment by moyogii** [comment]
To add on #1 also is not a bug, it's just not supported and I looked at it for the last update.
