### ISSUE TITLE
Mining features (hi im french)

### ISSUE THREAD

**Issue by antonin129** [Monolith-RP/issues#240]
i am french , so i'm playing on the french monolith , idk if it's the same as the US serveur (and of course my english is pretty bad)

but , **i really dont like the mining uptade**, directly **mining mineral** _(idk what it is spell in EN sry)_ isn't RP at all
 so i propose something , instead of have our own crusher and all , just **have a hydrolic press that smash the ore** , its could be **located not far from the mine entrance _(the small house at the end of the tracks)_**
 
 the press will smash the ore for making **4 Mineral Powder et 1 pulverised rock** , and have a rate of **0.75/1second**
 and **the acces of this house will be totally free, everyone can use it only for themself (so no theft) , and re-add the mining rp**
 
 
 **like that we dont have the problem of the $42k crusher which is impossible to have when we start the game
 -we dont have a magical transformation of ore into mineral 
 and it's way faster than the crusher (so it's  #not boring)**
 
 i really hope that you can do that :)

**Comment by DevulTj** [comment]
The crusher was removed and replaced with a mining furnace that's much much cheaper.

**Comment by antonin129** [comment]
> The crusher was removed and replaced with a mining furnace that's much much cheaper.

Yes but not rp, you cant just mine and got pure mineral ready to be smelt.

That why I propose a **hydrolyc press, place by the server**
Like the Npc

 in the un-use small house at the mine entrance. _(The one at the start of the tracks)_

And personal use
like premium chest. (So player can't steal other player ore while it's smash)

It's still cheap (because its totally free to use, and always at the same spot)
Fast ( 1.5sc per ore)
And player don't have an inert skill that make him mine pure mineral directly ready to be smelt

**Comment by DevulTj** [comment]
Beyond the scope of Monolith RP.
