### ISSUE TITLE
Extend monopages time by paying for it.

### ISSUE THREAD

**Issue by Ace-Carter** [Monolith-RP/issues#243]
### Describe The Feature

- make it cost 2k and it stays up until next restart.

### Why Would You Like This Feature?

Monopages are not used as much and nobody checks them anymore cause its always emptry

### Suggested Solution

pay to make it stay up until next restart.

### Considered Alternatives

extend the up-time to 6 hours if online or not

**Comment by DevulTj** [comment]
yeah

**Comment by DevulTj** [comment]
time is until you leave now
