### ISSUE TITLE
Headlight color change one time payment

### ISSUE THREAD

**Issue by xWaller19** [Monolith-RP/issues#248]
### Describe The Feature

Allow color change of headlights whenever changing the R,G,B values after only paying once so the color can be changed after that, inf. amount of times, to different color(s). 75k for one color, each time is ridiculous to me.

### Why Would You Like This Feature?

Its pretty dumb how, lets say I have a yellow car with yellow headlights, then change the car color to pink, and then have to pay another 75k to change the headlights so it doesnt look ugly af.

**Comment by DevulTj** [comment]
This is already the case.
