### ISSUE TITLE
Underglow change

### ISSUE THREAD

**Issue by xWaller19** [Monolith-RP/issues#249]
### Describe The Feature

Allow buying underglow like cosmetics work at the clothing store. Buy it once, and can switch between underglows as long as they're purchased without paying again, PER VEHICLE.

### Why Would You Like This Feature?

Just a nice QOL or whatever you want to call it. Sometimes we like changing the colors of cars, and making the underglow look good with it, is also nice, but pretty dumb to have to buy it again over and over.

**Comment by DevulTj** [comment]
Added.
