### ISSUE TITLE
F.B.I

### ISSUE THREAD

**Issue by stillermond** [Monolith-RP/issues#253]
### Describe The Feature

The F.B.I should be a branch of P.D that is only available during States of Emergency, similar to that of SWAT. F.B.I would primarily be first responders to hostage situations, corrupt government officials, heavy PD casualties. They will be better armed, better trained, carefully selected, and more feared then SWAT. 

### Why Would You Like This Feature?

SWAT isn't feared by the community, when SWAT arrives on scene, nobody really cares. They are outdated, bugged, and unreliable. If we were to add F.B.I, we can make it so that only the mayor can deploy agents in Monoford. Or they can act on their own. F.B.I would be a fun option for cop-mains that are max PD level. It would mean that F.B.I agents are better trained and have more experience then any of the other PD force. And the nice thing is that there doesn't need to be many F.B.I agents, because of this we can make F.B.I whitelisted. 

### Suggested Solution

F.B.I positions only available during States of Emergency. F.B.I agents are held to high standards and must follow the rules made for them carefully. Only max-level police players can get the position for F.B.I agents. 
Give F.B.I agents strong weapons and access to a large assortment of weapons. 

### Considered Alternatives

Make SWAT more powerful

**Comment by DevulTj** [comment]
Nah, we're not gonna add FBI
