### ISSUE TITLE
MP5 Extended mag reset bug

### ISSUE THREAD

**Issue by Gamer3232** [Monolith-RP/issues#254]
### Describe The Bug

MP5 Extended mag reset

### To Reproduce

1. Go to PD locjer
2. Click on Mp5a equip extended mag
4. It has 30 bullets in the mag but if u unequip it then re-equip it it has 0 in the mag and it goes to your reserve ammo. 
locker

### Expected Behavior

To not unload your ammo every time you unequip in then reequip it like every other gun.

**Comment by DevulTj** [comment]
Fixed
