### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Motocarter82** [Monolith-RP/issues#255]
### Describe The Feature

Adding buyable apartments that you can use as a place to store things.

### Why Would You Like This Feature?

It doesn't make sense from a rp perspective to store automatic weapons and drugs in a bank. This will help people who need the extra room whether that be because they do everything or they like to stock up on tons of things like coca leaves or ores, so that way they don't have to worry about them for a while. In my case I do everything like crafting, drugs, and making food so having the extra storage would allow me to make more and store more.

### Suggested Solution

Ways that this could be implemented are having to purchase an apartment that you could either add storage with a menu like the bank does, or it could be more in-depth by having players make or buy storage racks to put in their house like gun racks, shelves, or storage chests.

### Considered Alternatives

Another way this could be implemented is by upgrading the storage in the bank, this could be done in game currency or could be done with purchasing more slots with mono-coins.

**Comment by DevulTj** [comment]
I don't think we'll do this.
