### ISSUE TITLE
Forums Thread Deletion

### ISSUE THREAD

**Issue by AidZ679** [Monolith-RP/issues#261]
### Describe The Feature

It seems you cant delete your own threads on the forums or i am just stupid and its an intended feature or i cant find the button, 
but of there isnt one there should be one or at least a button to request the deletion of a posted thread.

### Why Would You Like This Feature?

i would like this feature because it is very easy to accidentally post in the wrong section and it would be very nice if i would be able to remove my posts that are accidentally posted in the wrong section.

### Suggested Solution

add a button for thread deletions.

### Considered Alternatives

if its intended for moderation purposes add a button to request the deletion of a thread.

**Comment by moyogii** [comment]
Issues are specific to the game mode only as a result. I will be closing this.
