### ISSUE TITLE
EMS changes

### ISSUE THREAD

**Issue by Brentsie** [Monolith-RP/issues#262]
### Describe The Feature

Budget:

A locker that uses ems budget. This locker will include adrenalines and defibrillators.

At the moment adrenalines are expensive and while you may say just get an ambulance and take them to hospital. Some people simply fall over and die from lack of hunger. I like to carry adrenaline as a medic to make situations quick and easy instead of time consuming for the other party.

Defibrillators and CPR being on hand at all times pretty much makes CPR pointless for medics. Having a defib be an item that uses budget is much more explanatory.

Service:
Hospital should require paperwork similar to police database. This database would have check ins and outs and injuries people had.

If someone comes in for heals they will be required to wait for you to fill out the form and then find out what's wrong with them and list those problems on the report.

This will make hospital life more realistic without people coming in screaming for heals.

### Why Would You Like This Feature?

I want the roleplay on the server to go back to its roots.

In 2017 and 2018 this server had quality police and emergency services roleplay and by this I mean interns and cadets had to prove they could roleplay and the systems were shown and trained before someone was able to rp properly.

Now its turning into quick job done rp. There needs to be longer situations that keeps people from just killing eachother because every roleplay scenario ends in less than 5 minutes.

### Suggested Solution

A database similar to police database that both police and ems can view to see who checks in and out. 

It will be fail rp not to follow the procedure.

**Comment by pmxpt** [comment]
This is actually nice. I don't know if we are going to implement everything, but the locker idea is good in my opinion.
