### ISSUE TITLE
Tricycle

### ISSUE THREAD

**Issue by anthonycicanese** [Monolith-RP/issues#263]
### Describe The Bug

My tricycle always spawns at 0%. An admin took it to a repair shop to try and fix it and it wouldn't work. The wrench wouldn't fix it either.

### To Reproduce

1. Go to 'Garage'
2. Click on 'Spawn tricycle'
3. Click on 'Get in tricycle'

### Expected Behavior

It will be smoking and be at 0% health

**Comment by DevulTj** [comment]
Fixed
