### ISSUE TITLE
Lockable Hospital doors

### ISSUE THREAD

**Issue by Brentsie** [Monolith-RP/issues#264]
### Describe The Feature

Being able to lock all the doors in the hospital as paramedics+
This will provide better roleplay of people making appointments to the hospital. they will have to wait and then i will call them in for medical attention.

This means that the spawnpoint for deaths will go to the lobby and not the back of the hospital.

### Why Would You Like This Feature?

I believe citizens being able to just run around the hospital is fail roleplay. while i'm able to call the police them spawning there and running around in the hospital without the EMS actually having any power over their own hospital.

Similar to police department we need control over the hospital to make better roleplay.

### Suggested Solution

Lockable doors in hospital

**Comment by pmxpt** [comment]
This is already done I believe.
