### ISSUE TITLE
Rework deputy weapon loadout

### ISSUE THREAD

**Issue by MCP430** [Monolith-RP/issues#265]
### Describe The Feature

Change the weapon load-out of Pine county deputies, later 2 is very open I believe they should be given an AR-15 primary and an MP5 primary the shotgun isn’t very good especially in the open areas of L2. Also increase the level required to become a deputy to bring the new load-out in-line with other PD jobs.

### Why Would You Like This Feature?

It would give PC deputies more versatility and provide a much needed buff as they are higher than police 3 yet their weapons are that of an officer 1 which makes no sense given they are a SD.

### Suggested Solution

Give pine county deputies the AR-15 and perhaps the MP5 (idk about the MP5 tho but at least the AR-15)

**Comment by DevulTj** [comment]
I gave them an AR-15 for now.
