### ISSUE TITLE
More pvp

### ISSUE THREAD

**Issue by MONOLITHSUGGESTS** [Monolith-RP/issues#267]
### Describe The Feature

There should be more places to raid, more things to do pvp wise, I'm thinking more craftable weapons. Maybe a casino raid. 

### Why Would You Like This Feature?

End game gets very boring, Its just pvp over again, add more things for pvp.

### Suggested Solution

none

### Considered Alternatives

None

**Comment by Brentsie** [comment]
End game is pvp over again so u suggest more pvp?
this suggestion doesnt make sense mate.

**Comment by MONOLITHSUGGESTS** [comment]
> End game is pvp over again so u suggest more pvp? this suggestion doesnt make sense mate.

Everyone loves PVP, Yes I am suggesting more thing to PVP with.

**Comment by Brentsie** [comment]
But you quite literally just said "End game gets very boring, Its just pvp over again" 
so why do u want even more "pvp over again"
