### ISSUE TITLE
Player owned businesses and bring back deeds.

### ISSUE THREAD

**Issue by Brentsie** [Monolith-RP/issues#270]
### Describe The Feature

Add the ability to own various stores and bring deeds for houses.

### Why Would You Like This Feature?

The deeds on rentable houses and locations were a good part of this server. It allowed players to own a piece of the server and set their own prices accordingly to gain a little bit of profit.

Adding the ability to own a business in the city is a cool suggestion with gas stations etc anyone who owns them will have to keep it stocked using their own money and then set the prices accordingly to gain profits. The UPS drivers work well with this suggestion to keep stock when requested by a shop owner.

**Comment by moyogii** [comment]
We have no plans to bring back deeds at this time. However, I will keep the other part of this suggestion open

**Comment by DevulTj** [comment]
I think this feature is beyond the scope of Monolith RP for the next couple years.
