### ISSUE TITLE
Job payouts inline with other methods

### ISSUE THREAD

**Issue by Brentsie** [Monolith-RP/issues#273]
### Describe The Feature

ever thought about making jobs more rewardable such as bus drivers getting paid for finishing a route, taxi drivers get paid for driving to random parts of the map, secret service get bonus money for being close proximity of the mayor.

I feel like increasing citizen job payouts would increase value to the other jobs instead of just doing coke to get nicer cars. Everything should be similar in price but ofcourse cocaine being superior. UPS drivers getting 300-700 dollars per job every 2 minutes plus the commute is worthless.

### Why Would You Like This Feature?

Rewarding players for being these type of jobs will encourage them to play and enjoy them. Right now it only offers xp > money.
People enjoying what they do = better roleplaying.

**Comment by DevulTj** [comment]
I think we've got a subset of issues to solve here.

- [ ] Paramedics should get XP and cash from healing, reviving, and taking patients to the Hospital to be saved.
- [ ] Delivery drivers should get more cash from doing their missions.
- [x] More XP and cash from medic missions, firefighter missions, and police missions.

**Comment by DevulTj** [comment]
And to note, Bus Drivers are already paid for routes.

**Comment by Brentsie** [comment]
Sounds good to me. Also just making everything that is doable in the server worthwhile such as woodcutting its completely useless right now.

**Comment by moyogii** [comment]
@DevulTj @Brentsie I went ahead and did some beginning changes for addressing payouts for cash and XP for Medic, Fire and Police missions. We can see how this pans out over the next few days/week and see if it needs more. This should be a big jump for those getting into the game. This is present in the next patch 2.0.15

**Comment by DevulTj** [comment]
I've also made some changes.
