### ISSUE TITLE
Uncloseable Doors

### ISSUE THREAD

**Issue by TheGreatWolf14** [Monolith-RP/issues#274]
### Describe The Bug

Doors at Trailer park and bathroom doors at Motel do not close when property is owned

### To Reproduce

1. Go to Trailer Park or Motel
2. Rent either one and open doors
3.  Attempt to close the doors
4. See bug

### Expected Behavior

Expected doors to close with ease like other doors. Not have doors stuck open

**Comment by DevulTj** [comment]
Fixed in development
