### ISSUE TITLE
Add one Industrial plug to all House Garages

### ISSUE THREAD

**Issue by TheGreatWolf14** [Monolith-RP/issues#276]
### Describe The Feature

There is a lack of industry as there is only 4 places u can rent for your factory stuff. Make the car garages on the estate houses have one plug in garage

### Why Would You Like This Feature?

There is a heavy lack of factory buildings/ those with Indus plugs. Which is stressing out players.

### Suggested Solution

Add a Industrial plug to all the garages attached to the houses in Riverden.

### Considered Alternatives

There is a small radio shack in the woods that might fit one plug

**Comment by moyogii** [comment]
This has been done and its only in the suburban houses and not in any other properties and will be present in update 2.0.15
