### ISSUE TITLE
Inaccurate Clothing Store Placement on Mono-Map

### ISSUE THREAD

**Issue by kevint024** [Monolith-RP/issues#278]
### Describe The Bug

As of right now, the mono map shows that the Clothing NPC is located directly next to the hardware NPC, but it is actually further up the strip by the jewelry store. 

### To Reproduce

1. Open mono-phone
2. Click on mono map
3. Zoom into map and see that it is in the incorrect location

### Expected Behavior

Clothing store should be located where the purple waypoint is instead of down by the red wrench.

![20220205154331_1](https://user-images.githubusercontent.com/46543508/152660036-70a2387d-ffe2-4e48-ba85-bded07b0e334.jpg)

**Comment by moyogii** [comment]
It's in accurate due to the map being slightly off. We are aware of this.
