### ISSUE TITLE
More ore with mining

### ISSUE THREAD

**Issue by Jordan135134** [Monolith-RP/issues#279]
### Describe The Feature

I was wondering if possibly we could add atleast 1 ore per hit making out to 26 ore per vein, 

### Why Would You Like This Feature?

Back when it was chunks sure it took more time smelting wise but collecting material was a very good legal money maker for some and now its slow and pretty much limited to if you want some guns or got a few hours im thinking atleast doubling it now could balance mining to be better

### Suggested Solution

double ore per hit while mining or maybe triple but double would be great

### Considered Alternatives

With this I cannot see another alternative

**Comment by yowhatup17r** [comment]
Huge +1 I am a big fan of mining and I do it for the profits and I find it fun but it is very annoying having to go from ore to ore and it takes forever and it is not worth it for the time it takes

**Comment by DevulTj** [comment]
No it's already easier with this update.
