### ISSUE TITLE
Quest reward bug

### ISSUE THREAD

**Issue by CallMeBazaar** [Monolith-RP/issues#280]
### Describe The Bug

When you go to the quest in your inventory and start the quest homely compromises and focus on it then once you rent the building you will receive the reward and and the xp but once you complete it you can restart it and start the quest again and receive the rewards again leading to an infinity money/xp system.

### To Reproduce

1. Go to your inventory
2. Click on the quest
3. focus on the homely compromises
3. find an property
4. rent it
5. you get and reward
6. Error is you can repeat the steps above infinitely 

### Expected Behavior

I think you should make it where you can complete it but only can do it once to fix this from happening.

**Comment by Brentsie** [comment]
Thanks for being sensible to report this asap.

**Comment by moyogii** [comment]
Thank you for the report. This will be fixed on next server restart
