### ISSUE TITLE
New Car

### ISSUE THREAD

**Issue by RemyP7** [Monolith-RP/issues#281]
### Describe The Feature

Add some bike and new vehicule

### Why Would You Like This Feature?

In real life seeing motorcycles or quads are not rare so I propose this addition to add some RP

### Suggested Solution

Have some Bike, kart and quad for more RP

### Considered Alternatives

More content (addons):
Quad: https://steamcommunity.com/sharedfiles/filedetails/?id=309880608
Scooter: https://steamcommunity.com/sharedfiles/filedetails/?id=1581068979
Tmax: https://steamcommunity.com/sharedfiles/filedetails/?id=1659975424
Kart: https://steamcommunity.com/sharedfiles/filedetails/?id=2228601321
SuperMot: https://steamcommunity.com/sharedfiles/filedetails/?id=1652952973
Moto Cross: https://steamcommunity.com/sharedfiles/filedetails/?id=1611137323
Moto cross 2: https://steamcommunity.com/sharedfiles/filedetails/?id=1735177715
Moto de sport pack: https://steamcommunity.com/sharedfiles/filedetails/?id=1122464324
There would also be a motorcycle modified to be given to MPD but to a patrol with motorcycle training: https://steamcommunity.com/sharedfiles/filedetails/?id=824835884

**Comment by Brentsie** [comment]
i would like to see biker clubs lol

**Comment by DevulTj** [comment]
have you tried these bikes ingame though, they're really bad

**Comment by Brentsie** [comment]
> have you tried these bikes ingame though, they're really bad

i have yes. its a shame. Maybe S&box mono will have biker clubs
