### ISSUE TITLE
LR-300

### ISSUE THREAD

**Issue by MONOLITHSUGGESTS** [Monolith-RP/issues#282]
### Describe The Bug

When I get out the car or have a lr-300 equipped it turns into semi automatic and gets me killed. 

### To Reproduce

1. Equip Lr-300 
2. Get out of the car mid gun fight
3. Pull your lr-300 out and realise its in semi automatic
4. Die

### Expected Behavior

It should go into semi automatic or not fire

### Additional Context

Im not sure if its just equiping your gun in the car or already having it equipped before you get in

**Comment by BombasticTyrant** [comment]
+1 can confirm tho idk if there is anything they can do besides re-coding it
