### ISSUE TITLE
Riverden Hospital Doors

### ISSUE THREAD

**Issue by DKDiamond04** [Monolith-RP/issues#284]
### Describe The Feature

make the doors open state longer and a larger area to detect when a person walks up, it would be much better for EMS.

### Why Would You Like This Feature?

The doors at the hospital currently are automatic and they also have a pole in the way to block people from driving in their, especially with the changed drag stuff the stretchers get affected and often get stuck in the door as they don’t stay open long enough.

### Suggested Solution

Make the doors stay open longer and larger field to detect when someone walks up (not sure if this is even possible to change)

### Considered Alternatives

Change the doors to swinging doors instead of sliding doors or just outright remove the doors.

**Comment by DKDiamond04** [comment]
Honestly making the doors not collidable would also work

**Comment by moyogii** [comment]
I can look into this for the next map update. Ill add it onto the list and see what I can do

**Comment by DevulTj** [comment]
This also should be the case with PD doors.
