### ISSUE TITLE
Lykan Hypersport Passenger seat missing

### ISSUE THREAD

**Issue by xWaller0119** [Monolith-RP/issues#285]
### Describe The Bug

When someone is driving a lykan hypersport, a passenger can not enter the passenger seat. It only has one seat as of the new update.

### To Reproduce

Sit in driver seat of lykan, have another person try to get in car. Doesn't work.

### Expected Behavior

Have a passenger seat that is functionable.

**Comment by DevulTj** [comment]
VCMod can only fix this
