### ISSUE TITLE
Trunk capacity

### ISSUE THREAD

**Issue by Jordan135134** [Monolith-RP/issues#286]
### Describe The Feature

Upgrade Trunks For SUV's

### Why Would You Like This Feature?

Because normal sedan's have 4 space vans have 20 don't you think reasonably SUV trunks would carry more than the same as sedans like 8?

### Suggested Solution

upgrade SUV's to  8 trunk space

### Considered Alternatives

6 space for SUV's

**Comment by DevulTj** [comment]
Not gonna happen, sorry
