### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by MONOLITHSUGGESTS** [Monolith-RP/issues#288]
### Describe The Feature

The game performance on Riverden is really bad ngl, The ping is double the ping on monoford, the longer the server is up the more unplayable it is for everyone. Not just me.

### Why Would You Like This Feature?

So I can actually play 

### Suggested Solution

Fix the performance issues

### Considered Alternatives

Change back and add something new instead of a weak performance map

**Comment by moyogii** [comment]
The performance on this map is better than most I have played on throughout monoliths history and its not as simple as "Fix the performance issues" we are always looking for ways to optimize and improve the performance across the board for all players and will continue to do so every update where we can.
