### ISSUE TITLE
ADDD THE FKN HELLCAT/DODGECHARGER FOR CIVS

### ISSUE THREAD

**Issue by NekoBANDZ** [Monolith-RP/issues#289]
### Describe The Feature

add the 2015 dodge charger to the car dealership.
or add this dodge charger hellcat addon

https://steamcommunity.com/sharedfiles/filedetails/?id=1803754886

### Why Would You Like This Feature?

https://steamcommunity.com/sharedfiles/filedetails/?id=390056021
This dodge charger is already in the content pack and wouldnt really take much to add it to the car dealership and it doesn't have any lights or anything, and the other one is just more customizable and its a hellcat both would be amazing cars to add plz add

**Comment by DevulTj** [comment]
bodygroups are the issue

**Comment by DevulTj** [comment]
done
