### ISSUE TITLE
remove infinite ammo for gl on cop

### ISSUE THREAD

**Issue by ifknhategithubgobacktomonoforums** [Monolith-RP/issues#291]
### Describe The Feature

its the most op thing in the whole world especially on riverden when everything is long range and there is no reason to give swat out to 7 people one of them having a gl and two of them have snipers that one shot and all of them combined have gas masks in built. 

### Why Would You Like This Feature?

to give cops only one gl ammo per life it is op af

### Suggested Solution

give cops one gl round 

### Considered Alternatives

give cops one gl round

**Comment by moyogii** [comment]
This has already been implemented
