### ISSUE TITLE
LOWE DA RTR MUSTANG 

### ISSUE THREAD

**Issue by NekoBANDZ** [Monolith-RP/issues#302]
### Describe The Feature

a mustang https://steamcommunity.com/sharedfiles/filedetails/?id=1700580773

### Why Would You Like This Feature?

**THIS CAR IS HELLA DRIPPY**
Theres only like one mustang and it is really underpowered, Outdated and doenst look good either nobody really drives it i would love for this to be added because it would add more variety for choices in mustangs The rtr Mustang would be perfect

**Comment by DevulTj** [comment]
No sorry
