### ISSUE TITLE
Cant sell coppor in more units.

### ISSUE THREAD

**Issue by Ariyanqwq** [Monolith-RP/issues#305]
### Describe The Bug

i tried selling my copper on the mono market but it didn't wanna sell.

i had around 4 stacks and 30. but  it wouldn't sell. no matter what. so i made a report and Administrator (Broken) took my report. he said he had never seen this. and then i found out. i can only sell 1 unit per. unclaim it on the mono blackmarket. and then sell 2 units. and then unclaim it ETC. and i had around 250+  copper. i was not going to  claim and unclaim every copper by hand. so he told me to make a bug report. please fix this.

### To Reproduce

.

### Expected Behavior

.

### Additional Context

.

### Log Output

```shell
\.
```

**Comment by louiefox** [comment]
Seems like this could have been a few reasons, it does send notifications to the user if there is an error but only through a console message. I have fixed some issues related to the max price not being very obvious. If you can get this to happen again then check your console for messages.
