### ISSUE TITLE
Due to deeds being removed, property app no longer functions correctly in the MonoPhone

### ISSUE THREAD

**Issue by m4rkey** [Monolith-RP/issues#79]
### Describe The Bug

[monolith_additional_modules] addons/monolith_additional_modules/lua/monolith_modules/monophone/apps/cl_monophone_properties_app.lua:130: attempt to call method 'updatePropertyDeedData' (a nil value)
  1. SetProperty - addons/monolith_additional_modules/lua/monolith_modules/monophone/apps/cl_monophone_properties_app.lua:130
   2. DoClick - addons/monolith_additional_modules/lua/monolith_modules/monophone/apps/cl_monophone_properties_app.lua:54
    3. unknown - addons/monolith_additional_modules/lua/monolith_modules/monophone/cl_monophone_meta.lua:587 (x4)

### To Reproduce

1. Open the Monophone
2. Open the Property app and select a property.

### Expected Behavior

You should be able to select a property and rent it without issue.

**Comment by m4rkey** [comment]
This started occurring after deeds were deleted out of the gamemode.

**Comment by DevulTj** [comment]
I'll fix that now
