### ISSUE TITLE
Property Mailboxes

### ISSUE THREAD

**Issue by DevulTj** [Monolith-RP/issues#82]
### Describe The Feature

Add mailboxes to properties.

Apartment properties will have a shared mailbox.

### Why Would You Like This Feature?

Collect paychecks and monomarket orders here.

### Suggested Solution

Self explanatory.

**Comment by R4K0** [comment]
Yeah - this is perfect.

Devul is right - I have some good, custom-made 3d assets for Eagle Post addon done and even the addon is done in like 80% of it (although given the chance I'd rather re-make the system, it's not really.... maintainable code)

I have 5 assets:
The postal box
The amazon-locker style lockers
The delivery drone (Could offer this as an expensive option to deliver things to premium players)
The delivery drone box
The post-it note "sorry we missed you" that goes on the doors

You can see some of the assets in here.
https://www.youtube.com/watch?v=46OOv48-v9A

![image](https://user-images.githubusercontent.com/17243415/131883443-783c01be-8de7-4519-bd6c-cfc65f782311.png)

**Comment by DevulTj** [comment]
Implemented
