### ISSUE TITLE
Notification related bug on MonoPhone

### ISSUE THREAD

**Issue by m4rkey** [Monolith-RP/issues#88]
### Describe The Bug

[monolith_additional_modules] addons/monolith_additional_modules/lua/monolith_modules/monophone/notifications/cl_notifications.lua:19: attempt to index field 'title' (a nil value)
  1. v - addons/monolith_additional_modules/lua/monolith_modules/monophone/notifications/cl_notifications.lua:19
   2. Run - lua/includes/modules/hook.lua:84
    3. InsertNotification - gamemodes/monolithrp/gamemode/modules/notifications/cl_notifications.lua:268
     4. func - gamemodes/monolithrp/gamemode/modules/notifications/cl_notifications.lua:283
      5. unknown - lua/includes/extensions/net.lua:32

### To Reproduce

Unknown, server related error that seemed to happen when messing with notifcations.

### Expected Behavior

It should not error out.

**Comment by DevulTj** [comment]
Fixed
